// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/search-drugs.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.98.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/search-drugs.ts
var search_drugs_default = defineTool({
  name: "search_drugs",
  title: "Cari obat",
  description: "Cari obat di inventaris apotek berdasarkan nama, kandungan aktif, atau kategori. Mengembalikan stok, satuan dasar, harga jual, dan rak.",
  inputSchema: {
    query: z.string().trim().describe("Kata kunci nama obat / kandungan aktif. Kosongkan untuk semua obat."),
    limit: z.number().int().describe("Jumlah maksimum hasil (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = supabaseForUser(ctx);
    const take = Math.min(Math.max(limit || 20, 1), 100);
    let q = supabase.from("drugs").select("id, name, active_ingredient, category, stock, base_unit, sell_price, min_stock, rack").order("name").limit(take);
    if (query) q = q.or(`name.ilike.%${query}%,active_ingredient.ilike.%${query}%,category.ilike.%${query}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { drugs: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/low-stock.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var low_stock_default = defineTool2({
  name: "low_stock_report",
  title: "Laporan stok menipis",
  description: "Daftar obat yang stoknya berada pada atau di bawah stok minimum, untuk perencanaan pengadaan.",
  inputSchema: {
    limit: z2.number().int().describe("Jumlah maksimum hasil (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("drugs").select("id, name, category, stock, min_stock, base_unit, rack").order("stock", { ascending: true }).limit(500);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const take = Math.min(Math.max(limit || 50, 1), 200);
    const low = (data ?? []).filter((d) => Number(d.stock) <= Number(d.min_stock)).slice(0, take);
    return {
      content: [{ type: "text", text: JSON.stringify(low) }],
      structuredContent: { items: low, count: low.length }
    };
  }
});

// src/lib/mcp/tools/sales-summary.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
var sales_summary_default = defineTool3({
  name: "sales_summary",
  title: "Ringkasan penjualan",
  description: "Ringkasan omzet penjualan pada rentang tanggal tertentu: total transaksi, total omzet, rata-rata nilai transaksi, dan rincian per metode pembayaran.",
  inputSchema: {
    start_date: z3.string().trim().describe("Tanggal mulai ISO (YYYY-MM-DD). Kosongkan untuk 30 hari terakhir."),
    end_date: z3.string().trim().describe("Tanggal akhir ISO (YYYY-MM-DD). Kosongkan untuk hari ini.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ start_date, end_date }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = supabaseForUser(ctx);
    const end = end_date || (/* @__PURE__ */ new Date()).toISOString().slice(0, 10);
    const start = start_date || new Date(Date.now() - 30 * 864e5).toISOString().slice(0, 10);
    const { data, error } = await supabase.from("transactions").select("id, date, total, payment_method, kasir").gte("date", start).lte("date", `${end}T23:59:59`).order("date", { ascending: false }).limit(2e3);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = data ?? [];
    const total = rows.reduce((s, r) => s + Number(r.total || 0), 0);
    const byMethod = {};
    for (const r of rows) {
      const key = r.payment_method || "lainnya";
      byMethod[key] = byMethod[key] || { count: 0, total: 0 };
      byMethod[key].count += 1;
      byMethod[key].total += Number(r.total || 0);
    }
    const summary = {
      start_date: start,
      end_date: end,
      transaction_count: rows.length,
      total_revenue: total,
      average_transaction: rows.length ? Math.round(total / rows.length) : 0,
      by_payment_method: byMethod
    };
    return {
      content: [{ type: "text", text: JSON.stringify(summary) }],
      structuredContent: summary
    };
  }
});

// src/lib/mcp/tools/stock-card.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^3.25.76";
var stock_card_default = defineTool4({
  name: "get_stock_card",
  title: "Kartu stok obat",
  description: "Riwayat kartu stok (masuk, keluar, koreksi) untuk sebuah obat berdasarkan nama, termasuk batch, tanggal kedaluwarsa, dan stok akhir.",
  inputSchema: {
    drug_name: z4.string().trim().describe("Nama obat (pencocokan sebagian diperbolehkan)."),
    limit: z4.number().int().describe("Jumlah maksimum baris (default 30).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ drug_name, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = supabaseForUser(ctx);
    const take = Math.min(Math.max(limit || 30, 1), 100);
    const { data, error } = await supabase.from("stock_cards").select("id, date, drug_name, type, qty, unit, batch, exp_date, stock_after, source, user").ilike("drug_name", `%${drug_name}%`).order("date", { ascending: false }).limit(take);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { entries: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "szojizbycdttszrjldly";
var mcp_default = defineMcp({
  name: "pharmacy-pro-suite",
  title: "Pharmacy Pro Suite",
  version: "0.1.0",
  instructions: "Tools untuk Apotek Dinadawi (ApotekPro). Gunakan `search_drugs` untuk mencari obat & stok, `low_stock_report` untuk obat yang perlu dipesan, `get_stock_card` untuk riwayat mutasi stok satu obat, dan `sales_summary` untuk ringkasan omzet penjualan. Semua data dibaca sebagai pengguna yang sedang masuk.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [search_drugs_default, low_stock_default, stock_card_default, sales_summary_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
